### ISSUE TITLE
space lost around <embed>

### ISSUE THREAD

**Issue by unhammer** [TinoDidriksen/Transfuse#16]
```
$ echo 'a <embed> e' |apertium -f html spa-eng
To<embed>And</embed>
```
expected:
```
To <embed> And</embed>
```
(or maybe `To <embed/> And`)

Full example was something like
```
<p>See <embed data-content-id="123" data-link-text="Spot" data-resource="concept" data-type="inline"> run.</p
```

**Comment by unhammer** [comment]
[tfspace.zip](https://github.com/TinoDidriksen/Transfuse/files/6583292/tfspace.zip)
```
$ cd /tmp
$ unzip ~/Downloads/tfspace.zip
$ $ tf-inject --keep -f html < /tmp/tfspace/repro
a<embed>e</embed>
$ cat /tmp/tfspace/repro
[transfuse:\/tmp\/tfspace\/repro.d]

[tf-block:1-j7FMRw]

a .[]

[tf-block:2-y6Sc6A]

 e
.[]

```

The spaces survived the regular pipeline, but were then removed by `tf-inject`. (I notice if I delete the NUL's before passing on to tf-inject, the spaces are retained (or actually copy-paste from terminal and not notice that there are in fact NUL's :)).)

**Comment by TinoDidriksen** [comment]
This seems to have been fixed at some point, probably in https://github.com/TinoDidriksen/Transfuse/commit/9201d891c76837b70ed0e292f60ea5efc9390b68
